config/routes.rb
Rails.application.routes.draw do


  post'likes/:post_id/create' => 'likes#create'
  post'likes/:post_id/destroy' => 'likes#destroy'

  post'users/:id/update'=>'users#update'
  get'users/:id/edit'=>'users#edit'
  post 'users/create'=>'users#create'
  get 'signup'=>'users#new'
  get 'users/index'=>'users#index'
  get 'users/:id'=>'users#show'
  post'login'=>'users#login'
  post'logout'=>'users#logout'
  get'login'=>'users#login_form'
  get 'users/:id/likes' => 'users#likes'

  get 'posts/index'=>'posts#index'
  get 'posts/new'=>'posts#new'
  get'posts/:id'=> 'posts#show'
  post'posts/create'=>'posts#create'
  get'posts/:id/edit'=>'posts#edit'
  post'posts/:id/update'=>'posts#update'
  post'posts/:id/destroy'=>'posts#destroy' 

  get '/' => 'home#top'
  get 'about' => 'home#about'
    
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member
    get :followers, on: :member
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
    
    has_secure_password

    validates :name, {presence: true}
    validates :email,{presence: true,uniqueness:true}

    def posts
        return Post.where(user_id:self.id)
    end



    has_many :relationships, foreign_key: :"following_id"
    has_many :followings, through: :relationships, source: :follower

    has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: :"follower_id"
    has_many :followers, through: :reverse_of_relationships, source: :following

    def is_followed_by?(user)
        reverse_of_relationships.find_by(following_id: user.id).present?
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user,{only:[:index,:show,:edit,:update]}
  before_action :forbid_login_user,{only:[:top]}
  before_action :ensure_correct_user,{only: [:edit,:update]}

  def index
    @users = User.all
  end

  def followings
    user =User.find(params[:id])
    @users =user.followings
  end

  def followers
    user =User.find(params[:id])
    @users =user.followers
  end

  def show
    @user=User.find_by(id:params[:id])
  end

  def new
    @user=User.new
  end

  def create
    @user = User.new(
      name: params[:name],
      email: params[:email],
      image_name:"top.png",
      password: params[:password]
      )
    if @user.save
      session[:user_id]=@user.id
      flash[:notice]="ユーザー登録が完了しました"
      redirect_to("/users/#{@user.id}")
    else
      puts '---------------'
      puts @user.errors.full_messages
      puts '---------------'
      render("/users/new")
    end  
  end

  def edit
    @user=User.find_by(id:params[:id])
  end

  def update
    @user=User.find_by(id: params[:id])
    @user.name= params[:name]
    @user.email=params[:email]
    if params[:image]
      @user.image_name="#{@user.id}.jpg"
      image=params[:image]
      File.binwrite("public/user_images/#{@user.image_name}",image.read)
    end
    if @user.save
      flash[:notice] ="ユーザー情報を編集しました"
      redirect_to("/users/#{@user.id}")
    else
      puts '---------------'
      puts @user.errors.full_messages
      puts '---------------'
       render("users/edit")
    end
  end

  def login_form
  end

  def login
    @user= User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
        session[:user_id]= @user.id
        flash[:notice]="ログインしました"
        redirect_to("/posts/index")
    else
        @error_message="メールアドレスまたはパスワードが間違っています。"
        @email=params[:email]
        @password=params[:password]
        puts '---------------'
        puts @user.errors.full_messages
        puts '---------------'
        render("users/login_form")
    end
  end

  def logout
    session[:user_id]=nil
    flash[:notice]="ログアウトしました"
    redirect_to("/login")
  end

  def likes
    @user=User.find_by(id: params[:id])
    @likes=Like.where(user_id: @user.id)
  end

  def ensure_correct_user
    if @current_user.id != params[:id].to_i
      flash[:notice]="権限がありません"
      redirect_to("/posts/index")
    end
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="main users-edit">
  <div class="container">
    <div class="form-heading">アカウント編集</div>
    <div class="form users-form">
      <div class="form-body">
         <% @user.errors.full_messages.each do |message| %>
            <div class="form-error">
              <%= message %>
            </div>
         <% end %>

          <%= form_tag("/users/#{@user.id}/update",{multipart: true}) do%>
            <p>ユーザー名</p>
            <input name="name" value="<%= @user.name %>" >
            <p>画像</p>
            <input name='image' type='file'>
            <p>メールアドレス</p>
            <input name="email" value="<%= @user.email %>" >
            <input type="submit" value="保存">
          <%end%>
      </div>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<div class="main users-follow">
    <div class="container">
        <div class="row justify-content-center">
            <h1>FOLLOWERS</h1>
            <table class="table text-center">
            <thead>
                <tr>
                    <th>Name</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            <% @users.each do |user| %>
                <tr>
                <td>
                    <%= link_to user_path(user) do %>
                        <%= user.name %>
                    <% end %>
                </td>
                <td>
                    <% if user = @current_user %>
                        <% if user.is_followed_by?(@current_user) %>
                            <%= link_to user_relationships_path(user), method: :delete, class: "btn btn-danger" do %>
                                フォロー解除
                            <% end %>
                        <% else %>
                            <%= link_to user_relationships_path(user), method: :post, class: "btn btn-primary" do %>
                                フォロー
                            <% end %>
                        <% end %>
                    <% end %>
                </td>
                </tr>
            <% end %>
            </tbody>
            </table>
        </div>
    </div>
</div>

app/views/users/followings.html.erb
<div class="main users-follow">
  <div class="container">

      <h1>FOLLOWING</h1>
      <table class="table text-center">
        <thead>
          <tr>
            <th>Name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= link_to user_path(user) do %>
                  <%= user.name %>
                <% end %>
              </td>
              <td>
                <% if user = @current_user %>
                  <% if user.is_followed_by?(@current_user) %>
                    <%=link_to user_relationships_path(user), method: :delete do %>
                      <button type="button" class="btn btn btn-danger">フォロー解除</button>
                    <% end %>
                  <% else %>
                    <%=link_to user_relationships_path(user), method: :post do %>
                      <button type="button" class="btn btn btn-primary">フォロー</button>
                    <% end %>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    
  </div>
</div>

app/views/users/index.html.erb
<div class="main users-index">
  <div class="container">
    <h1 class="users-heading">ユーザー一覧</h1>
    <% @users .each do |user|%>
      <div class="users-index-item">
        <div class="user-left">
              <img src="<%="/user_images/#{user.image_name}"%>">
        </div>
        <div class="user-right">
          <%= link_to(user.name,"/users/#{user.id}")%>
        </div>
      </div>
    <% end%>
  </div>
  
</div>

app/views/users/likes.html.erb
<div class="main user-show">
  <div class="container">
    <div class="user">
      <img src="<%= "/user_images/#{@user.image_name}" %>">
      <h2><%= @user.name %></h2>
      <p><%= @user.email %></p>
      <% if @user.id == @current_user.id %>
        <%= link_to("編集", "/users/#{@user.id}/edit") %>
      <% end %>
    </div>
    
    <ul class="user-tabs">
      <li><%= link_to("投稿", "/users/#{@user.id}") %></li>
      <li class="active"><%= link_to("いいね!", "/users/#{@user.id}/likes") %></li>
    </ul>
    
    <% @likes.each do |like|%>
      <% post= Post.find_by(id: like.post_id) %>
      <div class="posts-index-item">
        <div class="post-left">
        <img src="<%= "/user_images/#{post.user.image_name}" %>">
        </div>
        <div class="post-right">
          <div class="post-user-name">
            <%= link_to(post.user.name, "/users/#{post.user.id}") %>
          </div>
          <%= link_to(post.content, "/posts/#{post.id}") %>
        </div>
      </div>
    <% end%>
  </div>
</div>

app/views/users/login_form.html.erb
<div class="main users-new">
  <div class="container">
    <div class="form-heading">ログイン</div>
    <div class="form users-form">
       <div class="form-body">
        <% if @error_message %>
            <div class="form-error">
              <%= @error_message %>
            </div>
        <% end %>
        <%=form_tag("/login") do%>
            <p>メールアドレス</p>
            <input name=email value="<%=@email%>">
            <p>パスワード</p>
            <input type='password' name=password value="<%=@passwoed%>">
            <input type="submit" value="ログイン">
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="main users-new">
  <div class="container">
    <div class="form-heading">新規ユーザー登録</div>
    <div class="form users-form">
       <div class="form-body">
            <% @user.errors.full_messages.each do |message| %>
             <div class="form-error">
                 <%= message %>
             </div>
            <% end %>
            <%=  form_with url:"/users/create" do |form|%>
               <p>ユーザー名</p>
               <input name="name" value="<%= @user.name%>">
               <p>メールアドレス</p>
               <input name="email" value="<%= @user.email%>">
               <p>パスワード</p>
               <input name="password" type="password" value="<%=@user.password%>">
               <input type="submit" value="新規登録">
            <%end%>
       </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="main user-show">
  <div class="container">
    <div class="user">
      <%= image_tag("/user_images/#{@user.image_name}")%>
      <h2><%= @user.name%></h2>
      <p><%= @user.email%></p>
      <% if @user.id==@current_user.id%>
        <%=link_to("編集","/users/#{@user.id}/edit")%>
      <%end%>
    </div>

    <div class="col-lg-6 col-md-8 mx-auto">
      <p class="text-small">
        <%= link_to "#{@user.followings.count} フォロー", followings_user_path(@user) %>
        <%= link_to "#{@user.followers.count} フォロワー", followers_user_path(@user) %> 
      </p>
      <% if @user == @current_user %>
        <p class="lead text-muted">You're @currently signed in as <%= @current_user.email %></p>
      <% else %>
        <% if @user.is_followed_by?(@current_user)%>
          <%= link_to user_relationships_path(@user),data: { "turbo-method": :delete },allow_other_host: true do %>
            <button class="btn btn-primary">フォロー解除</button>
          <% end%>
        <% else%>
          <%= link_to user_relationships_path(@user),data: { "turbo-method": :post },allow_other_host: true do %>
            <button class="btn btn-primary">フォロー</button>
          <% end%>
        <% end%>
      <% end %>
    </div>

    <ul class="user-tabs">
      <li class="active"><%= link_to("投稿", "/users/#{@user.id}") %></li>
      <li><%= link_to("いいね!", "/users/#{@user.id}/likes") %></li>
    </ul>
    
    <% @user.posts.each do |post|%>
      <div class="posts-index-item">
        <div class="post-left">
          <img src="<%= "/user_images/#{post.user.image_name}" %>">
        </div>
        <div class="post-right">
          <div class="post-user-name">
            <%= link_to(post.user.name, "/users/#{post.user.id}") %>
          </div>
            <%= link_to(post.content, "/posts/#{post.id}") %>
        </div>
      </div>
   <%end%>
  </div>
  </div>
</div>